### ISSUE TITLE
[Exercise 2] IntegrityError: duplicate key value violates unique constraint "tweetwordcount_pkey"

### ISSUE THREAD

**Issue by kfoley15** [UC-Berkeley-I-School/w205-spring-17-labs-exercises#24]
# Error
```
java.lang.Exception: Shell Process Exception: Python IntegrityError raised
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/storm/component.py", line 489, in run
    self._run()
  File "/usr/lib/python2.7/site-packages/streamparse-2.1.4-py2.7.egg/streamparse/storm/bolt.py", line 219, in _run
    self.process(tup)
  File "bolts/wordcount.py", line 79, in process
    cur.execute("INSERT INTO tweetwordcount (word,count) VALUES ('" + word + "',1)");
IntegrityError: duplicate key value violates unique constraint "tweetwordcount_pkey"
```
https://ucbischool.slack.com/files/jmkupe/F4M4MJZ41/-.txt

# Solutions

> (former w205 student -- exercises may be different, so take w/ a grain of salt & caveat lector)...if a row already exists in a table, it can't be inserted again (with the same key); some databases have an atomic "upsert" operation that does an "insert" if the row doesn't exist, else it does an "update" to the existing row. Failing that (if that isn't available, or no manually implemented function that does the same is to be used), then there are two options/work-arounds: (1) go ahead and insert duplicate rows, using a different, artificial key that is guaranteed unique; or, (2) check if the row exists & insert if it doesn't, else update existing row. The second option requires either locking, or sequential (not concurrent) access to the table to avoid a race condition.

https://ucbischool.slack.com/archives/C1VEY8QTA/p1490157733911510

> I'm working on a video for postgres "upsert" to give students some ideas of how to do this without giving the answer
> some other things to think about:
> for locking, the example code really does not lock using "select ... for update", which probably we really should be doing (what if two processes select the count, add to the count, and then update? - one will overwrite the other's changes and the count will be short)
> for commits, the example code commits after every insert or update.  logically, this is probably correct database design as we are supposed to commit after every transaction.  I suppose 1 word count is a logical transaction in this case.   probably not for this exercise, but for future food for thought, we might want to re-architect it to commit every 1000 rows or so, subject to proper locking and coordination between multiple writers (easier said than done)

https://ucbischool.slack.com/archives/C1VEY8QTA/p1490193013128748

**Comment by kfoley15** [comment]
Resolved in Slack, links above
